# Generated by Django 5.2.7 on 2025-11-22 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='projects.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'tag'], name='projects_ta_project_72401e_idx')],
                'unique_together': {('project', 'tag')},
            },
        ),
    ]
