# Generated by Django 5.2.7 on 2025-11-22 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_issue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='thumbnail_url',
        ),
    ]
